modLoader="javafml"
loaderVersion="[43,)"

license="MIT License"

[[mods]]

modId="radadditions"
version="0.0.1-1.19.2"

displayName="radston12´s Additions"
logoFile=""
credits=""
authors="radston12"

description='''
A mod that adds my ideas to minecraft
'''

[[dependencies.radadditions]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.radadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
